server:
  port: 8080

eureka:
  client:
    enabled: true

spring:
  data:
    mongodb:
      database: admin
      host: mongo
      password: customer#123456
      port: 27017
      username: customer-api